### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Tuvqlu** [LatamPMDevs/Minerware#31]
Hey : D

can we set up Maps in game? With certain commands.

thank you so much for uploading this plugin : D

**Comment by JustJ0rd4n** [comment]
Hello @Tuvqlu, yes you can set up your own maps in game when you create a new arena. At this moment there's no official documentation or guide on how to use the plugin but soon there would be.

USE:
```
/minerware arenas create <world name>
```

**Comment by Tuvqlu** [comment]
Thanks so much, by the way will there be any additional minigames added? I think a few small PvP games could be beneficial :)

**Comment by JustJ0rd4n** [comment]
> Thanks so much, by the way will there be any additional minigames added? I think a few small PvP games could be beneficial :)

We have some minigames planned, you can check them out [here](https://github.com/LatamPMDevs/Minerware/blob/master/Microgames.md). But we are open for suggestions :)
