### ISSUE TITLE
Bugs

### ISSUE THREAD

**Issue by ricky074game** [LatamPMDevs/Minerware#34]
Plugin works very smoothly!

1. Language change, when you edit language files they delete the progress and do not change
2. Unopped players cannot join
3. Waitime is very long (not a bug ik)

**Comment by IvanCraft623** [comment]
1. The language files should not be edited, it is done on purpose, as new translations can be added/changed. In case you want to add/change a wrong translation, please create a PR.
2. Within the next commit it will be fixed.
3. Within the next commit it will be made configurable.

Thanks for your suggestions!

**Comment by Tuvqlu** [comment]
Of course! This is like the only minigame plugin that works smoothly so thankyou! Where in ur code is the language so I could find it, thanks

**Comment by IvanCraft623** [comment]
Fixed in 764f88fb0d2db48f61efa7831c59a6a957a800cf & dd7aa3d7a1770b72a18bb439797834236952e035
