### ISSUE TITLE
Questions

### ISSUE THREAD

**Issue by Tuvqlu** [LatamPMDevs/Minerware#36]
1. Will any new minigames come soon?
2. Could there be a command added where you can leave the arena, there could also be an item that shows up in your inventory when you join that you can leave with
3.

ty

**Comment by IvanCraft623** [comment]
1. Yes, new microgames will be added
2. No, we consider that this must be done by the server in which it is used, you can use some plugin in poggit.

**Comment by Tuvqlu** [comment]
Is there a command to leave?
