### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Tuvqlu** [LatamPMDevs/Minerware#39]
Make colorfloor first get 3 Pt then second one gets 2 then third get one point bc u tie too often.

also a winning command could be cool

**Comment by IvanCraft623** [comment]
> Make colorfloor first get 3 Pt then second one gets 2 then third get one point bc u tie too often.

This will be fixed as more microgames are added.

> also a winning command could be cool

I have no idea what you're talking about.

**Comment by Tuvqlu** [comment]
Like a reward for winning agame. Also, when you leave the game you still have the scoreboard, is there a command to leave?

**Comment by IvanCraft623** [comment]
> Also, when you leave the game you still have the scoreboard

This should have been reported as a bug

**Comment by Tuvqlu** [comment]
Oh sorry

**Comment by IvanCraft623** [comment]
> Like a reward for winning agame.

This should be done by a separate plugin
