### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Ihsan48** [LatamPMDevs/Minerware#51]
Here the crash dump

PocketMine-MP Crash Dump Wed May 25 08:06:27 CEST 2022

PocketMine-MP version: 4.3.4 [Protocol 503]
Git commit: 7bbb2617c8b0af24ffd6df86041e487eed9fb889
PHP version: 8.0.19
OS: Linux, android

THIS CRASH WAS CAUSED BY A PLUGIN

Error: SQL CONNECT error: Unable to open database: unable to open database file
File: plugins/Minerware_dev-86.phar/src/LatamPMDevs/minerware/libs/poggit/libasynql/libasynql
Line: 142
Type: LatamPMDevs\minerware\libs\poggit\libasynql\SqlError
Backtrace:
#0 plugins/Minerware_dev-86.phar/src/LatamPMDevs/minerware/database/DataManager(89): LatamPMDevs\minerware\libs\poggit\libasynql\libasynql::create(string[39] object(LatamPMDevs\minerware\Minerware), array[4], array[2])
#1 plugins/Minerware_dev-86.phar/src/LatamPMDevs/minerware/database/DataManager(65): LatamPMDevs\minerware\database\DataManager->createContext()
#2 pmsrc/src/utils/SingletonTrait(31): LatamPMDevs\minerware\database\DataManager->__construct()
#3 pmsrc/src/utils/SingletonTrait(36): LatamPMDevs\minerware\database\DataManager::make()
#4 plugins/Minerware_dev-86.phar/src/LatamPMDevs/minerware/Minerware(64): LatamPMDevs\minerware\database\DataManager::getInstance()
#5 pmsrc/src/plugin/PluginBase(95): LatamPMDevs\minerware\Minerware->onLoad()
#6 pmsrc/src/plugin/PluginManager(222): pocketmine\plugin\PluginBase->__construct(string[42] object(pocketmine\plugin\PharPluginLoader), string[25] object(pocketmine\Server), string[43] object(pocketmine\plugin\PluginDescription), string[99] /storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMine-MP/pl, string[114] phar:///storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMin, string[46] object(pocketmine\plugin\DiskResourceProvider))
#7 pmsrc/src/plugin/PluginManager(364): pocketmine\plugin\PluginManager->internalLoadPlugin(string[107] /storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMine-MP/pl, string[42] object(pocketmine\plugin\PharPluginLoader), string[43] object(pocketmine\plugin\PluginDescription))
#8 pmsrc/src/Server(1006): pocketmine\plugin\PluginManager->loadPlugins(string[86] /storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMine-MP/pl)
#9 pmsrc/src/PocketMine(304): pocketmine\Server->__construct(string[23] object(BaseClassLoader), string[35] object(pocketmine\utils\MainLogger), string[78] /storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMine-MP/, string[86] /storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMine-MP/pl)
#10 pmsrc/src/PocketMine(327): pocketmine\server()
#11 pmsrc(11): require(string[122] phar:///storage/emulated/0/Android/data/com.kpwnapps.pmmpplugins/files/PocketMin)

Code:
[133] 		if(!isset($dialect, $factory, $sqlMap[$dialect])){
[134] 			throw new ConfigException("Unsupported database type \"$type\". Try \"" . implode("\" or \"", array_keys($sqlMap)) . "\".");
[135] 		}
[136] 
[137] 		$pool = new SqlThreadPool($factory, $configData["worker-limit"] ?? 1);
[138] 		while(!$pool->connCreated()){
[139] 			usleep(1000);
[140] 		}
[141] 		if($pool->hasConnError()){
[142] 			throw new SqlError(SqlError::STAGE_CONNECT, $pool->getConnError());
[143] 		}
[144] 
[145] 		$connector = new DataConnectorImpl($plugin, $pool, $placeHolder, $logQueries ?? !libasynql::isPackaged());
[146] 		foreach(is_string($sqlMap[$dialect]) ? [$sqlMap[$dialect]] : $sqlMap[$dialect] as $file){
[147] 			$resource = $plugin->getResource($file);
[148] 			if($resource===null){
[149] 				throw new InvalidArgumentException("resources/$file does not exist");
[150] 			}
[151] 			$connector->loadQueryFile($resource);
[152] 		}

Loaded plugins:
AcidIsland 0.0.1 by BeeAZ-pm-pl for API(s) 4.0.0
EconomyAPI 5.7.3-PM4 by onebone for API(s) 4.0.0
LobbyCore 1.0.0 by Ihsan48 for API(s) 4.0.0
MultiWorld 1.7.0-beta4 by CzechPMDevs, VixikCZ, fuyutsuki, kaliiks for API(s) 4.0.0
NichiJoinLocation 2.0.0 by MadeAja for API(s) 4.0.0
PurePerms 2.0.2 by Vecnavium , 64FF00 & ProjectInfinity for API(s) 4.0.0
ScoreboardsDX 1.0.1 by ItsToxicGG, DanteDevs, Kostamax27 for API(s) 4.0.0
TeleportUi 1.0,0 by Ihsan48 for API(s) 4.0.0

uname -a: Linux localhost 4.14.190-perf-23866583-abA525FXXU4BVC2 #1 SMP PREEMPT Mon Mar 14 21:34:06 KST 2022 aarch64
Zend version: 4.0.19
Composer libraries: 
- adhocore/json-comment 1.1.2@fc2f76979f0a44a5f5bc2a2b600d0762fe0e78e7
- brick/math 0.9.3@ca57d18f028f84f777b2168cd1911b0dee2343ae
- daverandom/callback-validator unknown@unknown
- fgrosse/phpasn1 v2.4.0@eef488991d53e58e60c9554b09b1201ca5ba9296
- netresearch/jsonmapper v4.0.0@8bbc021a8edb2e4a7ea2f8ad4fa9ec9dce2fcb8d
- pocketmine/bedrock-data 1.7.0+bedrock-1.18.30@c8f323ff0cbdb36a5d95e7e4a23969f562445be0
- pocketmine/bedrock-protocol 9.0.1+bedrock-1.18.30@9d3cc87c4d26c002dd42aa9af20c0cd47a72018e
- pocketmine/binaryutils 0.2.4@5ac7eea91afbad8dc498f5ce34ce6297d5e6ea9a
- pocketmine/callback-validator 1.0.3@64787469766bcaa7e5885242e85c23c25e8c55a2
- pocketmine/classloader 0.2.0@49ea303993efdfb39cd302e2156d50aa78209e78
- pocketmine/color 0.2.0@09be6ea6d76f2e33d6813c39d29c22c46c17e1d2
- pocketmine/errorhandler 0.6.0@dae214a04348b911e8219ebf125ff1c5589cc878
- pocketmine/locale-data 2.5.0@df6fc7f2b48850b306c60466a11f7a27bb8fe1de
- pocketmine/log 0.4.0@e6c912c0f9055c81d23108ec2d179b96f404c043
- pocketmine/log-pthreads 0.4.0@61f709e8cf36bcc24e4efe02acded680a1ce23cd
- pocketmine/math 0.4.2@aacc3759a508a69dfa5bc4dfa770ab733c5c94bf
- pocketmine/nbt 0.3.2@3e0d9ef6b6c5fb45e3745a121296e75631b3eefe
- pocketmine/pocketmine-mp 4.3.4@7bbb2617c8b0af24ffd6df86041e487eed9fb889
- pocketmine/raklib 0.14.4@1ea8e3b95a1b6bf785dc27d76578657be4185f42
- pocketmine/raklib-ipc 0.1.1@922a6444b0c6c7daaa5aa5a832107e1ec4738aed
- pocketmine/snooze 0.3.1@0ac8fc2a781c419a1f64ebca4d5835028f59e29b
- ramsey/collection 1.2.2@cccc74ee5e328031b15640b51056ee8d3bb66c0a
- ramsey/uuid 4.3.1@8505afd4fea63b81a85d3b7b53ac3cb8dc347c28
- rhumsaa/uuid unknown@unknown
- symfony/polyfill-ctype v1.25.0@30885182c981ab175d4d034db0f6f469898070ab
- symfony/polyfill-php81 v1.25.0@5de4ba2d41b15f9bd0e19b2ab9674135813ec98f
- webmozart/assert 1.10.0@6964c76c7804814a842473e0c8fd15bab0f18e25
- webmozart/path-util 2.3.0@d939f7edc24c9a1bb9c0dee5cb05d8e859490725

----------------------REPORT THE DATA BELOW THIS LINE-----------------------

===BEGIN CRASH DUMP===
eNrtPIly20aWv9KhXRuphgduApxSRookJ9qxYo0lT7JjupwG0CARgQCCBiQxU/n3fe914yClOMd4
pra2nIrLQKP79buvbvqfo6SoNrx+fycqmRb5aOGMR3W6EaOF6bm24/pzfz41bcc0vPGoKdUnY+qZ
XmC6gWNatu8Ytj0eZVzW51VVVKPFP0f1toRpo5e85puryzNxJ5fLTZqL6p5XYrnM0hAGymK1Smt6
43Kb/5gtl9c/ZgrGeLQRUvIVQrn+20t2+uqbb85Pb5jArwv2JudhJlhdsKIUOYthH4AhFqx5+gNL
0kwA0KTJshf4uBiVa14tZrOZrIsK9pmJTZPxWsQzY3aSx1WRxjNcPYuKzfS2vM95WcppudmUZdas
0lzOEKScXRXRragvgbbJ5dWs/XbZ0vo+FncT35vibjNZRbMBS2YdR2bIkJnix6xjR/8Ey0vEXmP+
79kENshgLgjesUAHKh7B89vRM4P90Q1b7s/O4OGS58Dm6sAPDhfsdytG97hYRJUAOR3Iukrz1Vs7
eMeK8AcR1Qe/BLRD+3DMeFXx7VvnXftkvTsEup+ZH5dGz/0Aje2K5XKwZPKFIuu0yGvxUB8QVhYr
N7gz/mnqNJOzayA5E3WR31Q8rQ9s8/fv8/59VOTAvCbSu9i/uov3e3dZLDb8Vijwzh9mbTf/wHN+
PwYrUV8AnTyPNCLugE6F0uyK/voSFh8EHxJZh8nkiyJ/WfBYQfR+CWKrB5ZlAdSSXASCA9Wm78tl
v/OuRLRWO1an1U+uBsYpCIiMqECx9ULLfXLhtajuhtMc+8Pw6e8zIaMqBZdf5P3KAOztY/vMDrhp
Ou/Yx3bMPdHeB4k+S+XtayGLporEVVXcpchYkvP81+Rsk4L+Mic740vBuqucZyg29amVuGnM/42M
/cP69LsVhRjmDximVO/ANAzvt/Eo63gjW+b43sfnDSEaDBDtJxzYxr48FRVP2qrVswjt+RQSIbnP
RvtpsyR3C+6FI+NXq+GKuf+xSe5A/9u4aRq/wE5rvsdOqZRCrTLVqgMTo1klfmzSqgvvpmV9fI9w
OHr383gk/s8nq/+xdA+4oXZ5n+Z3RXYnNiKvYesYJBHVo/YrjMBzVMQC2WbaNgws62WdJgefpVKK
+uB5nPIMlozZ84RHIK4tPMkfs0tevm2/vTs8/CeAgZpCL1/W9boq7lku7hnkP0m6On+IBLmTg+Xo
TS6bsiwqkHfPIRQZWy6Xo+f4hA9TdlNtaWg5YlOWbsoM8IT1OMSKSn/Sed/7W7GVBxqzw0NYoCZO
l6PDPxNyrkbuZ3rzFOmmPdfDz8uiyNgR4Qx6cLOG7C2+grGDAeEREYNZydvl6L6obsGDZOkG1Gj0
jv3lL8zUe/ka6P0aJH7wGcGGhLDI81NKCiHd0CwLOpY1MhOiRLdqKCiOMcTYMXvZaHhrLoG7Oals
C9CxnpBBq9cH7cNicX1z8tX5e63XQJmCCCnWEKJCw95Bw9GMc1p+IlNygRzS3EP2nLZjFyA2wJe0
TW+Df2VQi3xdZOBS4S0rVn9rRJUKiTz8bFAZpPKKR7dgh3GHjae3hSpX8Gh9kMr3yrMcPFZL9hf2
9tHoO7Z4rMGMS1BwEJbm4rzj4vNKZxBAnaaD+NQmFgdqmULO75ahlNqVR0dHOZSpGnQv8aGILvI7
nqXxSbVq0FSH9tKCkTPaisUFMCovaiYeUlm3+u0aHVwSlGv2JHQSUrEYmb3ForlHUcOwOlH//Klg
/FQwfioYPxWMnwrGTwXjp4LxU8H4/65gbGsgiaXPSZTGFzLjeYxvOcczkeHgeNQdp4yMqTE1YYQ3
9bqoJGZIXwpx8o9JuZmUGQLmZYqjDkw08F1QWQigE55JMR7FAqrDGFfCR1kk9dlwYMOpMCOYy2WP
xPAZaz1QMJh29er65ttXr1+ewdC9CGVaI+qYv52Dnhab7cnVxYCmweCQJnc6n9qTq0tnl64iFyH8
+Wg0aXjLpVBoANDlcgelX6XqZRGG21NI/gdE9WNDmkxCdYeei7XkOWTpH4seDW+57DAYPP4Wai6b
rE6/LapsqHeDwV165lNjEoqa70np9CcRrVXOAh/+nj6kt6f/oLOxbVPL5jaF51uoLtJb+dEoj3DP
chOrPAkRvkeEwZMNkf8g/eu6LiUYNST66yacgunOBpTMBoCAUd+k0Tr97wK9ZMRrYkjHr8ffhmyz
HqvBJbjmkx/4R2OGhrdcPsJEefY/wAkNcvaYNmDGVVOJK1Ft5IAJ/dg+8dYu8X8XUc7v0mbDxsxz
XrwwDPZfDLIdDE0XeZLmab39aJx5r3aACN+iN3j8LQZyHYElhQWvYnn23YDc3fF9s99zzxe1vCke
0uirr2D8jEMGpm3lrwWUBxv+YM0/GsU7iEHW0L/+FnJvRCawNfYmHdA6GNwjdPyf8m89CsPnX6cI
+5C8AjIg6SUMZzKOgBn/Qqax80YFJOw5meTF5D79CUDTmxR1DcmDnCqyJ1huhk2axfLIpAl6nOcy
Je481CJHvpJJqfAy8lGTApgOSO68Z2n4sMmGI9julXJnqIx2gcgfM+CKPRz6CQAN38Now+v1cCTi
GQgFSByOrZv8lvJGi7IRmyw8qrZlXQwHdBe8X9dUOwjGxQY9hGHYpmkFuj2d5kkxnARjILqdkboc
vq7inbfNzsc1lzvkYDEeo4wGYz9I0uaeueJOZHGoKTEUu2ORZEoIMIsGN6HKD4dLN6CVOkUziQeb
LXAdc7r2iXVzr69e7korr3e4QwvS4cjV2audFXHxnibtDypB76xc70qwLGT6sMMX0mm5M6emDjSO
OTqCVQJEiEq6ahQPW168Bu6A9053GSnXm2JHGtfYQxffXe4Qnq7CNOfVFsZAb6YeDNXFrcjTn3bF
vqfw8IroPZpzX6V7+rLltNIC4Gh6P6Ul+S4zmLro8cp1qXUO1UfkouLZMKwNrR1NBOqr/moTsMae
YjZEtj1aWMbcApIktpc6T1dWRV1EBUB1DRv2SPEgZB6GoeWZ88gPDZ5YTpLEXpz4nuGYwvHnQsRB
Evo+EtC0WWaaNw8sgzicrSFuMGdqwv+BMSlFlUws2/c817cnPDxxLffFd9+9cb78+6nFnpns+vKK
Xb0+P7+8umGXRc4uecVMh1nmwnYWhsf+en3DLMOyGOdVtPaQILwfNPQUgrTY6bRjXb4vZIsUOiB8
4cqp0pHOBpRMVO/BdiqOrXXkKY/XBcajGdrcBOboUyETzeU4iaxk7gXzIDG443A3ccPI4lboGUZs
zD0rEYaY+2KO7K7S6HamnZUxDab2ccTdeWz6iWH5ie8k8/k8tEzPj2IzMM3QiIWwbMfmgtwpCBBw
hTQHeJmFPLqdUPeb13h+Bwy/zYv7/Fj/jT5nVRVSihmQzWWOne07awrMOBYicUBKgRm7tnB94RlR
4LpOaAShaRkmIBXywApQq3NRV0IK5DDRv4FoQ5p6R/Z17IdhZFgm90UcWsLhc8GtxOexk/BAREEc
CSuJQj8m+23r2FkogOWAP8axNkf/UzsIfPWntnEc+Ylt2UliRGEc2h5348AVc9jDsgMvSFzPchw3
FMbToHv9HQUo/0fgg9iOIn8eObHlRYZhxbFjcR6AWhuREcXOnM+BF77YA09mT3GEhAgMPXZ5BKrP
A5MnIY/9OHICP3EjYTuR8KxgHrvCg898F9KTQsQ0zD72nLk/d0CpPC+MOPDU9X3Xcizhu5FlR5Yr
/Mh1ubUHEBsoWaHdC6JmHDuB4LZhB4EtkjgJ7SCKbcMSlul6sWsAaN8yAtDPPUhFVvQwQCsQfy+e
e4klbDv2fNOO7CC2gsiyIseLzLkw4z1s6NB3DfqaaXQ8ABVz2NrhhmM7fggaLnzLDESYmJabJCbQ
5Acokz10yHmIVlmsqYuQEi+J5okVgiK7RmgbXgReyPO4aSZzboGj8hNASuxDWhEuZAReFJhWZCSB
4bqRDwTYpuGLyIrNeRAGXuIYTgSYPoIwGQQZBcqDPYGNfpTYILDIcoQjwO4tHsUCuGVwE8zAjvaM
oHMEDrgRzqPInrsBdw2fe0GcgA2CaiZ8Pjd4OLftyI0CJ0x2QeRh3eYux7Yw4kAkXuhFbhI6rrDn
jstNC7IUT8xdzzZDGwx/jyP944SSEAoNx7/Dzw9gVfxWpWYG+njn2BTgFuwwACxCL0zmvhtH1hzU
yJ378CcUjum7iWM9BWWSlpGO1eZxYFnccxxwUJEXzWPOuYv/+7ZlGqB6InLmts/FHn9lXhQ/Cc0f
89jg4FDANc99M3LMgJuJ5wgwLyeG+OOiA3YDYQUhpgx8I8UWzaBPEMDXA5Mj+G/uCAHctXxIAUMw
JMcIXdNwPSH82A5DD7wJ74E0TRprvprHoKouT8A5gjnZoQ9u04Ul89C1eWSjm4xsZx5ZqP/VutlI
ztv1j7273G6SIt+CBLMt5JvZpE1d7wBVNBHbANMwfSsKYKPQnLuxExu2E4cG2A54Fz/wDVSup2BB
yPDNASw3Fk7IrdhBipMgjA1hBqHFwU7mjmm74BHA2/uJKmQ2BZQU9Qzckah0pMRY4QWeE81Bgr7h
+OAGfMcCwQkD5BKbEHIAMfC3lrsDpAQrmaC/JdO30fQDO0jmAnTJiUCMYRhEGCjdKDTc2AcfGTgB
ZDSuqqM6fZhuKaN6xrC3wNSdhKai7gDdNGFJUbGdxGmZP2M3a4h+rC2MGK8Eq9eCFbmQ8MBrFvEc
T5VDwdI8yhoweHhgqk87hSAE0bKGRAJhXRcbWJkggH2YkidizAr4UkkEyULwMLdsWzSVhsXShG2K
OE1S2gESEryTkm0R8DfivgM3g6SfN1kt2X2Rf14zjNeQOEG5W4DDSTHqbBHDep1KRff9WuSsKVcV
jwHAdJkv8xbYYpkz9uzbtUDE8IKOhIyKAQjdEgceQEoiqamsPhOqymHjbZNM1MQvyCzTSDAVD3Bk
g5CB45GYZBxT85VYMEo98YNcN3UMaj7RF4oWbDlSJwksyiBDi5cjwuwky4p7lqUSsW3PS9ldyhmd
1uOcH/Fhoj8tAN+Gdnh2ri4dqQ8M8GKY4zGQGDAFoYVbplmJ83Xl230eIPvsW7AY0AjgK49jBumS
Yj+yFRh+yzaCy6aiy0QMmB4KRBqYI35seIZsW6V3MBfygEawA70ppLaHCF3tKCYVdQ8mwHY871jA
Z9r7m2YTAldAq07kNo9uuLxl6oqNnNKEN8AtUu2WUpy2roq8aEB6MF2OGTUhmSoj0B7GDDNhIATr
BeIN2COObZo8VQ01BfyaxAs0gZZVxUMKGiaADUASaW7eIYe81QhdJKirOAd1cszS+nNgX13RsljU
oNWkMnuL2QHQ0IDdWMQWImOiKV0QqH1d5aQcVZPnKM4YC+SiJCGonsaUnYk7/cw26WoNxlxB6T0e
Gp9WHORIVTVlrUYVw5AxUDwLTRcJF4ySCoRYGQS/g8oC0H4aA9QR1DnI0lPQrulA0frWS6dpy3wj
YLutMsqvsiIE7cEeFFPjjO5UoW1vxIqH2xo4zq4Vqw1ibioRNi2/Qandp8R50igw2vuJAtQqmSQK
kxRQBI8E2OcEK6mEaLdUSg7SatBM2Qov2RRopqgVuNGK0FTXvRbMQCpgd3LBKov6P08BNvU+hP+a
V/G/hr+si5JQ0O6zQ0mDkwzcR4nRNO4Qwl1brEzDcjRi5AS+JavQ+MnPPwKGZBeEEnoMFjUQfHII
Pkw8iKgh51solJVFYrDqZouHCBJG2VOkHNerm/MFu/n64pq9vLi8uGEnV1cvL86v2dX5a/btq9d/
PX89ZjCJ3byCWefs269fvTxnV69fnZ5fX0/3XcAOPyzX0+y4ElVaUEBGRyyRwGgtyCUTNzpnawLv
ISWIybfQlAm4QqHcLIHCC0Zp3uCtVIx8v6hsSsnoCiPyBF2QmkaQFRBwvb0jVxGJ9niFMQTjPC2Y
Pp6NuqBb0iC2UkSYDijOIrpKrmptRwOolyhlT6ptaFrl4dMoacptTfmKVyFYxqTPhskBPc1dMjVE
R69iehX47g3PG0o+hphAYtaADuLx/dNK2KqhCq9JArAUvZveBKfslfL5SuEheyiaLO5wSSGI3Oes
x18qwCWhD4R6hqFphd1ekLN4FCRJdRSEjrakKjZtsFWr9YzJUDWHEkZqtCQf6QZ7QqV2tOO6TRhR
ZBXshGqoFTluNqXKrlQKx/SHCX5o5XWGk/QCwp3QbCnAy5z3AoydP8FgCNoQ+GCHO1AyKRuBjqFe
g9RWbbaJTgt367Eat4JUOYJOKqcKG5z6i3za8IcJNexli/spL3E03TQbiLEQXisETrfUUJAQp/m2
dZ09X9FeNCvJYh7rGCTbpcaINpxgFtxA0HU6iZ0V6tO+TmNuhF5PwVeTWxNSsPTEIWWUOUwiDvbZ
0XYGqFCuAukjcg+wUwmGglJyrEmYWqMo7KmDZZqfip52Z5zcZ7vIwAzLAA33w6A+pIfLPBc1Cmyh
QwSkZusiUylmyOtoTZk4oQxZE6iQDjLk21Tlo7+q0BKKLtlU4e3ZUErtJ3Sr1bZG4GM2MQcCJOHR
xpO6RUaHAPLafR5LRySYQsaKcqxlKNHHxTCo0ZqyryEXFHgvG5M7dnr1ZgxrAYcQ7Os+jUHtKVdQ
3rODPyH4C+a1aXefkUvizmDulJ3E4KjWPEtmUEqqMiEWoMN6K9iUYSsPFWxgiH3YGwAbliLnD+jV
MMXk2ZQhEm+u8qs22e4LQKwlEKl7CJu4sCnzcqLf96qbS211Mv1JdPLEtLwVo8SAp1MmSNuVegxC
qxNYatHhlF3pNRmvVrSA60pU6wLtmFR8hSSATIBtsswoY8HycgPIo7HzCuV0mqUwS9XLeP1JyJpd
3rwhTCWQhGSHTU23vkmU/XaquJi2vmZTNxNctSBsh/WhyOmIkGw9YdgYgFwIEtaWTKh/kySNpoyi
1JpjEoC/uuAQJ2ANHnLgD8vBTY0JFxDaHSG9Rk6A1yVHDCGakzuXSqQqlYC5tdZRpESo/oB2dbqa
OntFSdLZxfXJl5AfUT7V5KRD6LAb9JR0fqiShBSVUf+4JR7WGz2dva3HImxWi7Zo+4KZWKzplHUN
7oq+M12iS9VUQGvOZaGCt7YIE4EprBW003UBRTxaYVuribYaJy+OnV4m+V0bLeARSm/6Rl3gQRkP
iOHzWCVtuifzQ5HmqiFAnPqcfRcWD2j5Fbs4Ywffvbk4OwS5g9kDDjD/HsSGgkkh3INxYA1XxZo/
Kv0Aayh62eVg7d99+bKFr+u7wcjntBmegFHiQOLVqQjRVrQdIh1GHwC/Cd5IOCqShLaFb2mynTw0
adwLhPg52W3O3FB3RZma+jcMFA/I02u7aqTu8qi78mTxes1ErVkwfYCM26gQot2j3gVjIM9XXY2S
47JsPxSP21l3qbifdAH6qYaYYu7JpmjQeyQq1mlnAixrWYuxHb0jtUJA/PhMwRkWv6ZQPVhMhOdC
ld6hUMBCgT96ATfC70kpUEcVdFItHN4N+op83KgjH3wg4/uoAi0RRS2GP6l5CkvjaTR5BZBixlt1
B2Tbxfh3h4291+EJsyIi85VprGIG0sNBpqBwsgmHXFhhEIUZIlahk1660EatJq0cPIpEJqhSUOpN
u2bpLWyBdTJ5oowD6auquK/Xyo/BFpytFbSBkwPrl7UKyYQsnvJOWtQmPWsUaRdnckAXummUvILG
1FlnR6ZuObVpDq3ZERLAmwCKUCZ3b2kkumesBnrp9r2uTsDTxxLWHu2ep1TiQoRphFatsijVXVoS
uXrBJIDm6FhiW7gh1UZIOu2EYRjdGeQJuurAEd3dW+j8B5uRVHGrYZU+aHUDRHq3HfeeEM11gr9J
3BvqvMXusL5AMAj04CQm6kpdNxMP7BcKFbpgNE0Lwhj833aDFSPYd43N10j2qGPs0t9Z/51IIN/H
V6tKrHSfUTclVe8Ffzp1u08f4QcO6NXZK7zkrK8g6aQBfdq9UGUJp1+E4Y6SEO8JoLHp4CQAgnfH
+abEe0pKOI+YCgJV37WGQXqENwAowA2C0Ck27MWwwTeGiFGuOdiKQHdfIQ5tsgphJBEVFCQTdJY5
Rkj1tQ1oKpzwnYahvrwxiMANJOaQ8JDDbf2aBkhSVt/bPR5JVdE1FGudbvqwokM0AqVrG6D1GEVQ
iujbcUPqhOpFbdd72m+gvwx3aDn34SRARxglSWUBgwaThgHga83PtpW01oPK71VdeaFdBnbmoYKL
KTdKkw4QHnY3lTqGod8H6v6KcscAT7usNghDosalLt6eqexA6mqQqjiVeGHGHcdj2HMDqTFqADxB
DYvdYU5nKARFEfDshEn66ZgapoQW83Q8ZsKllLyq5E+vV+1wDeSwhaJeMbSDlseMmsvEBczOKwwa
PN/uowDTI0jHYX647Y5Q9o/CQO2kyJKpbkVgPqAp47kCpDo4KWnK23dQxmAAgaTpAHgqVExCxU8f
RL8zzVkOzugW2ApdjhTSyLD2aIbnn6u24TMQqNo5PlQiwCUL2LJF7bTlUCtQPX2sekgqC2vZz/4H
ZIXsBidFWyb67KDjkjLGFJ1wAzMOWiIO1W6Y440pcKJOocxwaksgooC8x/tdkMpPSUkJDq7DoruR
qikmi42g8vYJpmhUcAn9hlvtvNS/xMDh3SlKHXiIEYW93ePuu4EI8biqlx8eo2kTI2AH8lDJLa1J
G7XKY+oPs7RDgg300zv1FVyxlghl7bBuzPb3xQLkFlVnR6dVKsz1b3kBIXQ4z6nWx+Y3oQZRHJBs
54zZc4tckmqeY1OTiTpSeOKhGo+BbkClKAHQO9icfd8NA9ni4Xs2+YJ9D5/phdbdgiIg9k0agcUA
8nwL4rjA1o5KLHECgMMfryNAeu1h6XXfsz/B85NLce5y9H2HpEp0YEt8QYKfW+2ueGKMPgDryh8a
ibocCZiFyeNz67MWhR4KAQePB6lMHiuECOrucIfah+Dr2Z8Rqp3odH6PpykP+th1x5+oQzEO0gWt
iYuBXkMM0p6/Lnv+klqoWqWrZ4aH47vuizrLKnXDmCrqJ0sLprAhX4xNFOpI4u8iykzoukg3Szhe
7VT70rh6BIiYBDiGKjP6HRfsxcuTGzWI3ReBhw1/1hfLxm7wAIqei7H9EKdVPaZc9M+6+FXHz8M+
rkphMPeHwKKPWXijY24GoSraMvWDuaZqs862eVV1B9eUUgEc+rcB4q42ABCT9tAbJKk6Hc9eUC5F
W9H8HSDUKtAj7wcjEyq5B7VwodohJH+p+37RLXaOJPW4ILUL0yytt8qgOz1J8VfFmcqTVeBTVBJ8
KBarLhnFGyn7QsWrG1e9iNU/kEEXGJbgEJ+9qFJ2UlbMspgRLKxgYZvs9FzfEMUZm6KOj3ZjmrpR
gB/VbhNMNY7MwLStvcE7j4ZtHNYNk7SEwSLHkft1WosJuk8s32kz/qD7FfLIMnBkxbGjGosj2VR3
KdRfOKjuP3Sf9GI8ysIj7/a9vCv1RnGKvSbQ5O0RYdgpZpflH+GwahNgLDhSPy+q+taBiAdT8MLQ
0dn5i5M3L28GpNGVCb0l5cjoyfX7TmF/ZHo4Nuhe0Jz2QseRgFwe3kc//y9x/8nv
===END CRASH DUMP===

**Comment by IvanCraft623** [comment]
The android operating system does not support the necessary libraries to be able to use this plugin, use another operating system (Windows/Linux/MacOs)

**Comment by IvanCraft623** [comment]
Anyway PocketMine-MP does not support android officially

**Comment by Ihsan48** [comment]
Ummmmmm, ok. Thx for information
